server:
  port: 5000

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10097/eureka/
  instance:
    instance-id: zuul-gateway
    appname: ${spring.application.name}
    #prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


zuul:
  routes:
    eureka-client-api:
      path: /eureka-client-api/**
      serviceId: eureka-client

    feign-client-api:
      path: /feign-client-api/**
      serviceId: feign-client

  # 禁止直接访问具体服务API
  # 必须通过Zuul 访问
  ignored-patterns: /eureka-client/**, /feign-client/**
  ignored-headers: authKey

#logging:
#  level:
#    com.netflix: debug
